pipeline {
    //agent any
    agent {
        label 'AGENT-1'
    } 
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action')
    }

    stages {
        stage('init') { 
            steps {
                sh 'cd 00-vpc' 
                sh 'terraform init -reconfigure'
            }
        }
        stage('plan') { 
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
        stage('Deploy') { 
            when {
                 expression { env.GIT_BRANCH == 'origin/main' }
            }
            steps {
                    sh 'echo This is deploy'
            }
        }

        stage('Print Params') {
            steps {
                echo "Hello ${params.PERSON}"

                echo "Biography: ${params.BIOGRAPHY}"

                echo "Toggle: ${params.TOGGLE}"

                echo "Choice: ${params.CHOICE}"

                echo "Password: ${params.PASSWORD}"
            }
        }
        //  stage('Approval') {
        //     input {
        //         message "Should we continue?"
        //         ok "Yes, we should."
        //         submitter "alice,bob"
        //         parameters {
        //             string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        //         }
        //     }
        //     steps {
        //         echo "Hello, ${PERSON}, nice to meet you."
        //     }
        // }
    }


    post {
         always{
             echo "This section runs always"
             deleteDir()
        }
        success{
            echo " This section run when pipeline success"
        }
        failure{
            echo "This section run when pipeline failure"
        }
    }
}